// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events
  (id, at, actor_user_id, actor_token_id, action, target_type, target_id, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	ID           string
	At           int64
	ActorUserID  sql.NullString
	ActorTokenID sql.NullString
	Action       string
	TargetType   string
	TargetID     string
	Metadata     string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.At,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, at, actor_user_id, actor_token_id, action, target_type, target_id, metadata
  FROM audit_events
 WHERE (?2 = 0 OR actor_user_id = ?3)
   AND (?4 = 0 OR at >= ?5)
   AND (?6 = 0 OR at <= ?7)
 ORDER BY at DESC
 LIMIT ?
`

type ListAuditEventsParams struct {
	FilterActor interface{}
	ActorID     sql.NullString
	FilterSince interface{}
	Since       int64
	FilterUntil interface{}
	Until       int64
	Limit       int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents,
		arg.FilterActor,
		arg.ActorID,
		arg.FilterSince,
		arg.Since,
		arg.FilterUntil,
		arg.Until,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorTokenID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
