// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_pairings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteOldDevicePairings = `-- name: DeleteOldDevicePairings :execrows
DELETE FROM device_pairings
 WHERE status IN ('done','denied','expired')
   AND created_at < ?
`

func (q *Queries) DeleteOldDevicePairings(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldDevicePairings, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expirePendingDevicePairings = `-- name: ExpirePendingDevicePairings :execrows
UPDATE device_pairings
   SET status = 'expired'
 WHERE status = 'pending' AND expires_at < ?
`

func (q *Queries) ExpirePendingDevicePairings(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePendingDevicePairings, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDevicePairingByDeviceCode = `-- name: GetDevicePairingByDeviceCode :one
SELECT device_code, user_code, status, created_at, expires_at, user_id,
       requesting_ip, requesting_user_agent, requested_scopes,
       plaintext_token, token_id
  FROM device_pairings WHERE device_code = ?
`

func (q *Queries) GetDevicePairingByDeviceCode(ctx context.Context, deviceCode string) (DevicePairing, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingByDeviceCode, deviceCode)
	var i DevicePairing
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.RequestingIp,
		&i.RequestingUserAgent,
		&i.RequestedScopes,
		&i.PlaintextToken,
		&i.TokenID,
	)
	return i, err
}

const getDevicePairingByUserCode = `-- name: GetDevicePairingByUserCode :one
SELECT device_code, user_code, status, created_at, expires_at, user_id,
       requesting_ip, requesting_user_agent, requested_scopes,
       plaintext_token, token_id
  FROM device_pairings WHERE user_code = ?
`

func (q *Queries) GetDevicePairingByUserCode(ctx context.Context, userCode string) (DevicePairing, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingByUserCode, userCode)
	var i DevicePairing
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.RequestingIp,
		&i.RequestingUserAgent,
		&i.RequestedScopes,
		&i.PlaintextToken,
		&i.TokenID,
	)
	return i, err
}

const insertDevicePairing = `-- name: InsertDevicePairing :exec
INSERT INTO device_pairings
  (device_code, user_code, status, created_at, expires_at, user_id,
   requesting_ip, requesting_user_agent, requested_scopes,
   plaintext_token, token_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDevicePairingParams struct {
	DeviceCode          string
	UserCode            string
	Status              string
	CreatedAt           int64
	ExpiresAt           int64
	UserID              sql.NullString
	RequestingIp        string
	RequestingUserAgent string
	RequestedScopes     string
	PlaintextToken      sql.NullString
	TokenID             sql.NullString
}

func (q *Queries) InsertDevicePairing(ctx context.Context, arg InsertDevicePairingParams) error {
	_, err := q.db.ExecContext(ctx, insertDevicePairing,
		arg.DeviceCode,
		arg.UserCode,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UserID,
		arg.RequestingIp,
		arg.RequestingUserAgent,
		arg.RequestedScopes,
		arg.PlaintextToken,
		arg.TokenID,
	)
	return err
}

const markDevicePairingFetched = `-- name: MarkDevicePairingFetched :execrows
UPDATE device_pairings
   SET status = 'done',
       plaintext_token = NULL
 WHERE device_code = ? AND status = 'approved_unfetched'
`

func (q *Queries) MarkDevicePairingFetched(ctx context.Context, deviceCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDevicePairingFetched, deviceCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDevicePairingApproved = `-- name: UpdateDevicePairingApproved :execrows
UPDATE device_pairings
   SET status = 'approved_unfetched',
       user_id = ?,
       plaintext_token = ?,
       token_id = ?
 WHERE user_code = ? AND status = 'pending'
`

type UpdateDevicePairingApprovedParams struct {
	UserID         sql.NullString
	PlaintextToken sql.NullString
	TokenID        sql.NullString
	UserCode       string
}

func (q *Queries) UpdateDevicePairingApproved(ctx context.Context, arg UpdateDevicePairingApprovedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDevicePairingApproved,
		arg.UserID,
		arg.PlaintextToken,
		arg.TokenID,
		arg.UserCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDevicePairingDenied = `-- name: UpdateDevicePairingDenied :execrows
UPDATE device_pairings
   SET status = 'denied',
       user_id = ?
 WHERE user_code = ? AND status = 'pending'
`

type UpdateDevicePairingDeniedParams struct {
	UserID   sql.NullString
	UserCode string
}

func (q *Queries) UpdateDevicePairingDenied(ctx context.Context, arg UpdateDevicePairingDeniedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDevicePairingDenied, arg.UserID, arg.UserCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
