// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
)

const checkEventDuplicate = `-- name: CheckEventDuplicate :one
SELECT 1 FROM events
 WHERE source = ? AND delivery_id = ? AND received_at >= ?
 LIMIT 1
`

type CheckEventDuplicateParams struct {
	Source     string
	DeliveryID string
	ReceivedAt int64
}

func (q *Queries) CheckEventDuplicate(ctx context.Context, arg CheckEventDuplicateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEventDuplicate, arg.Source, arg.DeliveryID, arg.ReceivedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getEvent = `-- name: GetEvent :one
SELECT source, sequence, delivery_id, provider_timestamp, received_at,
       headers_json, body, body_sha256
  FROM events WHERE source = ? AND sequence = ?
`

type GetEventParams struct {
	Source   string
	Sequence int64
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.Source, arg.Sequence)
	var i Event
	err := row.Scan(
		&i.Source,
		&i.Sequence,
		&i.DeliveryID,
		&i.ProviderTimestamp,
		&i.ReceivedAt,
		&i.HeadersJson,
		&i.Body,
		&i.BodySha256,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events
  (source, sequence, delivery_id, provider_timestamp, received_at,
   headers_json, body, body_sha256)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	Source            string
	Sequence          int64
	DeliveryID        string
	ProviderTimestamp int64
	ReceivedAt        int64
	HeadersJson       string
	Body              []byte
	BodySha256        string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.Source,
		arg.Sequence,
		arg.DeliveryID,
		arg.ProviderTimestamp,
		arg.ReceivedAt,
		arg.HeadersJson,
		arg.Body,
		arg.BodySha256,
	)
	return err
}

const latestEventSequence = `-- name: LatestEventSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER) AS latest FROM events WHERE source = ?
`

func (q *Queries) LatestEventSequence(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestEventSequence, source)
	var latest int64
	err := row.Scan(&latest)
	return latest, err
}

const listEventSources = `-- name: ListEventSources :many
SELECT DISTINCT source FROM events ORDER BY source
`

func (q *Queries) ListEventSources(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEventSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var source string
		if err := rows.Scan(&source); err != nil {
			return nil, err
		}
		items = append(items, source)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEventSequence = `-- name: NextEventSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1 AS next_seq FROM events WHERE source = ?
`

func (q *Queries) NextEventSequence(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEventSequence, source)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const pruneAllEvents = `-- name: PruneAllEvents :execrows
DELETE FROM events WHERE received_at < ?
`

func (q *Queries) PruneAllEvents(ctx context.Context, receivedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAllEvents, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneEventsBySource = `-- name: PruneEventsBySource :execrows
DELETE FROM events WHERE source = ? AND received_at < ?
`

type PruneEventsBySourceParams struct {
	Source     string
	ReceivedAt int64
}

func (q *Queries) PruneEventsBySource(ctx context.Context, arg PruneEventsBySourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEventsBySource, arg.Source, arg.ReceivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readEventsSince = `-- name: ReadEventsSince :many
SELECT source, sequence, delivery_id, provider_timestamp, received_at,
       headers_json, body, body_sha256
  FROM events
 WHERE source = ? AND sequence > ?
 ORDER BY sequence ASC
 LIMIT ?
`

type ReadEventsSinceParams struct {
	Source   string
	Sequence int64
	Limit    int64
}

func (q *Queries) ReadEventsSince(ctx context.Context, arg ReadEventsSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, readEventsSince, arg.Source, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Source,
			&i.Sequence,
			&i.DeliveryID,
			&i.ProviderTimestamp,
			&i.ReceivedAt,
			&i.HeadersJson,
			&i.Body,
			&i.BodySha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
