// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteBootstrapInvite = `-- name: DeleteBootstrapInvite :exec
DELETE FROM invites WHERE bootstrap = 1
`

func (q *Queries) DeleteBootstrapInvite(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBootstrapInvite)
	return err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE code = ? AND consumed_at IS NULL
`

func (q *Queries) DeleteInvite(ctx context.Context, code string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvite, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBootstrapInvite = `-- name: GetBootstrapInvite :one
SELECT code, role, default_scopes, created_by_user_id, bootstrap,
       created_at, expires_at, consumed_at, consumed_by_user_id
  FROM invites
 WHERE bootstrap = 1
 LIMIT 1
`

func (q *Queries) GetBootstrapInvite(ctx context.Context) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getBootstrapInvite)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.Role,
		&i.DefaultScopes,
		&i.CreatedByUserID,
		&i.Bootstrap,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByUserID,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT code, role, default_scopes, created_by_user_id, bootstrap,
       created_at, expires_at, consumed_at, consumed_by_user_id
  FROM invites WHERE code = ?
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.Role,
		&i.DefaultScopes,
		&i.CreatedByUserID,
		&i.Bootstrap,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByUserID,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites
  (code, role, default_scopes, created_by_user_id, bootstrap,
   created_at, expires_at, consumed_at, consumed_by_user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInviteParams struct {
	Code             string
	Role             string
	DefaultScopes    string
	CreatedByUserID  sql.NullString
	Bootstrap        int64
	CreatedAt        int64
	ExpiresAt        sql.NullInt64
	ConsumedAt       sql.NullInt64
	ConsumedByUserID sql.NullString
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.Code,
		arg.Role,
		arg.DefaultScopes,
		arg.CreatedByUserID,
		arg.Bootstrap,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.ConsumedByUserID,
	)
	return err
}

const listInvites = `-- name: ListInvites :many
SELECT code, role, default_scopes, created_by_user_id, bootstrap,
       created_at, expires_at, consumed_at, consumed_by_user_id
  FROM invites
 ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.Code,
			&i.Role,
			&i.DefaultScopes,
			&i.CreatedByUserID,
			&i.Bootstrap,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ConsumedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitesByConsumed = `-- name: ListInvitesByConsumed :many
SELECT code, role, default_scopes, created_by_user_id, bootstrap,
       created_at, expires_at, consumed_at, consumed_by_user_id
  FROM invites
 WHERE (?1 = 1 AND consumed_at IS NOT NULL)
    OR (?1 = 0 AND consumed_at IS NULL)
 ORDER BY created_at DESC
`

func (q *Queries) ListInvitesByConsumed(ctx context.Context, consumed interface{}) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvitesByConsumed, consumed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.Code,
			&i.Role,
			&i.DefaultScopes,
			&i.CreatedByUserID,
			&i.Bootstrap,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ConsumedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBootstrapInvitesConsumed = `-- name: MarkBootstrapInvitesConsumed :execrows
UPDATE invites
   SET consumed_at = ?, consumed_by_user_id = ?
 WHERE bootstrap = 1 AND consumed_at IS NULL
`

type MarkBootstrapInvitesConsumedParams struct {
	ConsumedAt       sql.NullInt64
	ConsumedByUserID sql.NullString
}

func (q *Queries) MarkBootstrapInvitesConsumed(ctx context.Context, arg MarkBootstrapInvitesConsumedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markBootstrapInvitesConsumed, arg.ConsumedAt, arg.ConsumedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markInviteConsumed = `-- name: MarkInviteConsumed :execrows
UPDATE invites
   SET consumed_at = ?, consumed_by_user_id = ?
 WHERE code = ? AND consumed_at IS NULL
`

type MarkInviteConsumedParams struct {
	ConsumedAt       sql.NullInt64
	ConsumedByUserID sql.NullString
	Code             string
}

func (q *Queries) MarkInviteConsumed(ctx context.Context, arg MarkInviteConsumedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markInviteConsumed, arg.ConsumedAt, arg.ConsumedByUserID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
