// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AuditEvent struct {
	ID           string
	At           int64
	ActorUserID  sql.NullString
	ActorTokenID sql.NullString
	Action       string
	TargetType   string
	TargetID     string
	Metadata     string
}

type DevicePairing struct {
	DeviceCode          string
	UserCode            string
	Status              string
	CreatedAt           int64
	ExpiresAt           int64
	UserID              sql.NullString
	RequestingIp        string
	RequestingUserAgent string
	RequestedScopes     string
	PlaintextToken      sql.NullString
	TokenID             sql.NullString
}

type Event struct {
	Source            string
	Sequence          int64
	DeliveryID        string
	ProviderTimestamp int64
	ReceivedAt        int64
	HeadersJson       string
	Body              []byte
	BodySha256        string
}

type Invite struct {
	Code             string
	Role             string
	DefaultScopes    string
	CreatedByUserID  sql.NullString
	Bootstrap        int64
	CreatedAt        int64
	ExpiresAt        sql.NullInt64
	ConsumedAt       sql.NullInt64
	ConsumedByUserID sql.NullString
}

type ListenerToken struct {
	ID          string
	Name        string
	Scopes      string
	SecretHash  string
	CreatedAt   int64
	LastUsedAt  sql.NullInt64
	RevokedAt   sql.NullInt64
	OwnerUserID sql.NullString
	Kind        string
	Ephemeral   int64
	ExpiresAt   sql.NullInt64
}

type PushSubscription struct {
	ID                  string
	Source              string
	TargetUrl           string
	SigningSecretHash   string
	Name                string
	Cursor              int64
	PausedAt            sql.NullInt64
	CreatedAt           int64
	LastAttemptAt       sql.NullInt64
	LastSuccessAt       sql.NullInt64
	LastError           string
	ConsecutiveFailures int64
	OwnerUserID         sql.NullString
}

type User struct {
	ID            string
	Email         string
	Name          string
	Role          string
	PasswordHash  string
	DefaultScopes string
	CreatedAt     int64
	DeactivatedAt sql.NullInt64
	ExternalID    sql.NullString
}

type UserSession struct {
	ID         string
	UserID     string
	SecretHash string
	CreatedAt  int64
	LastUsedAt int64
	ExpiresAt  int64
	UserAgent  string
	Ip         string
}
