// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions WHERE id = ?
`

func (q *Queries) DeletePushSubscription(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPushSubscription = `-- name: GetPushSubscription :one
SELECT id, source, target_url, signing_secret_hash, name, cursor,
       paused_at, created_at, last_attempt_at, last_success_at, last_error,
       consecutive_failures, owner_user_id
  FROM push_subscriptions WHERE id = ?
`

func (q *Queries) GetPushSubscription(ctx context.Context, id string) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, getPushSubscription, id)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.TargetUrl,
		&i.SigningSecretHash,
		&i.Name,
		&i.Cursor,
		&i.PausedAt,
		&i.CreatedAt,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.LastError,
		&i.ConsecutiveFailures,
		&i.OwnerUserID,
	)
	return i, err
}

const insertPushSubscription = `-- name: InsertPushSubscription :exec
INSERT INTO push_subscriptions
  (id, source, target_url, signing_secret_hash, name, cursor,
   paused_at, created_at, last_error, consecutive_failures, owner_user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, '', 0, ?)
`

type InsertPushSubscriptionParams struct {
	ID                string
	Source            string
	TargetUrl         string
	SigningSecretHash string
	Name              string
	Cursor            int64
	PausedAt          sql.NullInt64
	CreatedAt         int64
	OwnerUserID       sql.NullString
}

func (q *Queries) InsertPushSubscription(ctx context.Context, arg InsertPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertPushSubscription,
		arg.ID,
		arg.Source,
		arg.TargetUrl,
		arg.SigningSecretHash,
		arg.Name,
		arg.Cursor,
		arg.PausedAt,
		arg.CreatedAt,
		arg.OwnerUserID,
	)
	return err
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, source, target_url, signing_secret_hash, name, cursor,
       paused_at, created_at, last_attempt_at, last_success_at, last_error,
       consecutive_failures, owner_user_id
  FROM push_subscriptions
 WHERE (?1 = 1 OR paused_at IS NULL)
 ORDER BY created_at ASC
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, includePaused interface{}) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptions, includePaused)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.TargetUrl,
			&i.SigningSecretHash,
			&i.Name,
			&i.Cursor,
			&i.PausedAt,
			&i.CreatedAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsByOwner = `-- name: ListPushSubscriptionsByOwner :many
SELECT id, source, target_url, signing_secret_hash, name, cursor,
       paused_at, created_at, last_attempt_at, last_success_at, last_error,
       consecutive_failures, owner_user_id
  FROM push_subscriptions
 WHERE owner_user_id = ?
   AND (?2 = 1 OR paused_at IS NULL)
 ORDER BY created_at ASC
`

type ListPushSubscriptionsByOwnerParams struct {
	OwnerUserID   sql.NullString
	IncludePaused interface{}
}

func (q *Queries) ListPushSubscriptionsByOwner(ctx context.Context, arg ListPushSubscriptionsByOwnerParams) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsByOwner, arg.OwnerUserID, arg.IncludePaused)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.TargetUrl,
			&i.SigningSecretHash,
			&i.Name,
			&i.Cursor,
			&i.PausedAt,
			&i.CreatedAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsBySource = `-- name: ListPushSubscriptionsBySource :many
SELECT id, source, target_url, signing_secret_hash, name, cursor,
       paused_at, created_at, last_attempt_at, last_success_at, last_error,
       consecutive_failures, owner_user_id
  FROM push_subscriptions
 WHERE source = ?
   AND (?2 = 1 OR paused_at IS NULL)
 ORDER BY created_at ASC
`

type ListPushSubscriptionsBySourceParams struct {
	Source        string
	IncludePaused interface{}
}

func (q *Queries) ListPushSubscriptionsBySource(ctx context.Context, arg ListPushSubscriptionsBySourceParams) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsBySource, arg.Source, arg.IncludePaused)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.TargetUrl,
			&i.SigningSecretHash,
			&i.Name,
			&i.Cursor,
			&i.PausedAt,
			&i.CreatedAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPushSubscriptions = `-- name: ListSystemPushSubscriptions :many
SELECT id, source, target_url, signing_secret_hash, name, cursor,
       paused_at, created_at, last_attempt_at, last_success_at, last_error,
       consecutive_failures, owner_user_id
  FROM push_subscriptions
 WHERE owner_user_id IS NULL
   AND (?1 = 1 OR paused_at IS NULL)
 ORDER BY created_at ASC
`

func (q *Queries) ListSystemPushSubscriptions(ctx context.Context, includePaused interface{}) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPushSubscriptions, includePaused)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.TargetUrl,
			&i.SigningSecretHash,
			&i.Name,
			&i.Cursor,
			&i.PausedAt,
			&i.CreatedAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pausePushSubscription = `-- name: PausePushSubscription :execrows
UPDATE push_subscriptions
   SET paused_at = ?
 WHERE id = ? AND paused_at IS NULL
`

type PausePushSubscriptionParams struct {
	PausedAt sql.NullInt64
	ID       string
}

func (q *Queries) PausePushSubscription(ctx context.Context, arg PausePushSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pausePushSubscription, arg.PausedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pausePushSubscriptionsByOwner = `-- name: PausePushSubscriptionsByOwner :execrows
UPDATE push_subscriptions
   SET paused_at = ?
 WHERE owner_user_id = ? AND paused_at IS NULL
`

type PausePushSubscriptionsByOwnerParams struct {
	PausedAt    sql.NullInt64
	OwnerUserID sql.NullString
}

func (q *Queries) PausePushSubscriptionsByOwner(ctx context.Context, arg PausePushSubscriptionsByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pausePushSubscriptionsByOwner, arg.PausedAt, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordPushFailure = `-- name: RecordPushFailure :execrows
UPDATE push_subscriptions
   SET last_attempt_at = ?,
       last_error = ?,
       consecutive_failures = consecutive_failures + 1
 WHERE id = ?
`

type RecordPushFailureParams struct {
	LastAttemptAt sql.NullInt64
	LastError     string
	ID            string
}

func (q *Queries) RecordPushFailure(ctx context.Context, arg RecordPushFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordPushFailure, arg.LastAttemptAt, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resumePushSubscription = `-- name: ResumePushSubscription :execrows
UPDATE push_subscriptions SET paused_at = NULL WHERE id = ?
`

func (q *Queries) ResumePushSubscription(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resumePushSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rotatePushSecret = `-- name: RotatePushSecret :execrows
UPDATE push_subscriptions SET signing_secret_hash = ? WHERE id = ?
`

type RotatePushSecretParams struct {
	SigningSecretHash string
	ID                string
}

func (q *Queries) RotatePushSecret(ctx context.Context, arg RotatePushSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rotatePushSecret, arg.SigningSecretHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePushCursorSuccess = `-- name: UpdatePushCursorSuccess :execrows
UPDATE push_subscriptions
   SET cursor = ?,
       last_attempt_at = ?,
       last_success_at = ?,
       last_error = '',
       consecutive_failures = 0
 WHERE id = ?
`

type UpdatePushCursorSuccessParams struct {
	Cursor        int64
	LastAttemptAt sql.NullInt64
	LastSuccessAt sql.NullInt64
	ID            string
}

func (q *Queries) UpdatePushCursorSuccess(ctx context.Context, arg UpdatePushCursorSuccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePushCursorSuccess,
		arg.Cursor,
		arg.LastAttemptAt,
		arg.LastSuccessAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePushOwner = `-- name: UpdatePushOwner :execrows
UPDATE push_subscriptions SET owner_user_id = ? WHERE id = ?
`

type UpdatePushOwnerParams struct {
	OwnerUserID sql.NullString
	ID          string
}

func (q *Queries) UpdatePushOwner(ctx context.Context, arg UpdatePushOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePushOwner, arg.OwnerUserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
