// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CheckEventDuplicate(ctx context.Context, arg CheckEventDuplicateParams) (int64, error)
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountActiveAdminsExcluding(ctx context.Context, id string) (int64, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) (int64, error)
	DeleteBootstrapInvite(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error)
	DeleteInvite(ctx context.Context, code string) (int64, error)
	DeleteOldDevicePairings(ctx context.Context, createdAt int64) (int64, error)
	DeletePushSubscription(ctx context.Context, id string) (int64, error)
	DeleteSession(ctx context.Context, id string) (int64, error)
	DeleteSessionsByUser(ctx context.Context, userID string) (int64, error)
	ExpireEphemeralTokensIdle(ctx context.Context, arg ExpireEphemeralTokensIdleParams) (int64, error)
	ExpirePendingDevicePairings(ctx context.Context, expiresAt int64) (int64, error)
	GetBootstrapInvite(ctx context.Context) (Invite, error)
	GetDevicePairingByDeviceCode(ctx context.Context, deviceCode string) (DevicePairing, error)
	GetDevicePairingByUserCode(ctx context.Context, userCode string) (DevicePairing, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetInviteByCode(ctx context.Context, code string) (Invite, error)
	GetPushSubscription(ctx context.Context, id string) (PushSubscription, error)
	GetSession(ctx context.Context, id string) (UserSession, error)
	GetToken(ctx context.Context, id string) (ListenerToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertDevicePairing(ctx context.Context, arg InsertDevicePairingParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertInvite(ctx context.Context, arg InsertInviteParams) error
	InsertPushSubscription(ctx context.Context, arg InsertPushSubscriptionParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertToken(ctx context.Context, arg InsertTokenParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	LatestEventSequence(ctx context.Context, source string) (int64, error)
	ListActiveTokens(ctx context.Context) ([]ListenerToken, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListEventSources(ctx context.Context) ([]string, error)
	ListInvites(ctx context.Context) ([]Invite, error)
	ListInvitesByConsumed(ctx context.Context, consumed interface{}) ([]Invite, error)
	ListPushSubscriptions(ctx context.Context, includePaused interface{}) ([]PushSubscription, error)
	ListPushSubscriptionsByOwner(ctx context.Context, arg ListPushSubscriptionsByOwnerParams) ([]PushSubscription, error)
	ListPushSubscriptionsBySource(ctx context.Context, arg ListPushSubscriptionsBySourceParams) ([]PushSubscription, error)
	ListSystemPushSubscriptions(ctx context.Context, includePaused interface{}) ([]PushSubscription, error)
	ListSystemTokens(ctx context.Context, includeRevoked interface{}) ([]ListenerToken, error)
	ListTokens(ctx context.Context, includeRevoked interface{}) ([]ListenerToken, error)
	ListTokensByOwner(ctx context.Context, arg ListTokensByOwnerParams) ([]ListenerToken, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	MarkBootstrapInvitesConsumed(ctx context.Context, arg MarkBootstrapInvitesConsumedParams) (int64, error)
	MarkDevicePairingFetched(ctx context.Context, deviceCode string) (int64, error)
	MarkInviteConsumed(ctx context.Context, arg MarkInviteConsumedParams) (int64, error)
	NextEventSequence(ctx context.Context, source string) (int64, error)
	PausePushSubscription(ctx context.Context, arg PausePushSubscriptionParams) (int64, error)
	PausePushSubscriptionsByOwner(ctx context.Context, arg PausePushSubscriptionsByOwnerParams) (int64, error)
	PruneAllEvents(ctx context.Context, receivedAt int64) (int64, error)
	PruneEventsBySource(ctx context.Context, arg PruneEventsBySourceParams) (int64, error)
	ReactivateUser(ctx context.Context, id string) (int64, error)
	ReadEventsSince(ctx context.Context, arg ReadEventsSinceParams) ([]Event, error)
	RecordPushFailure(ctx context.Context, arg RecordPushFailureParams) (int64, error)
	ResumePushSubscription(ctx context.Context, id string) (int64, error)
	RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error)
	RevokeTokensByOwner(ctx context.Context, arg RevokeTokensByOwnerParams) (int64, error)
	RotatePushSecret(ctx context.Context, arg RotatePushSecretParams) (int64, error)
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) (int64, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error
	UpdateDevicePairingApproved(ctx context.Context, arg UpdateDevicePairingApprovedParams) (int64, error)
	UpdateDevicePairingDenied(ctx context.Context, arg UpdateDevicePairingDeniedParams) (int64, error)
	UpdatePushCursorSuccess(ctx context.Context, arg UpdatePushCursorSuccessParams) (int64, error)
	UpdatePushOwner(ctx context.Context, arg UpdatePushOwnerParams) (int64, error)
	UpdateTokenOwner(ctx context.Context, arg UpdateTokenOwnerParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
