// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM user_sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM user_sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execrows
DELETE FROM user_sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, secret_hash, created_at, last_used_at, expires_at, user_agent, ip
  FROM user_sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO user_sessions
  (id, user_id, secret_hash, created_at, last_used_at, expires_at, user_agent, ip)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID         string
	UserID     string
	SecretHash string
	CreatedAt  int64
	LastUsedAt int64
	ExpiresAt  int64
	UserAgent  string
	Ip         string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.SecretHash,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_sessions
   SET last_used_at = ?,
       expires_at = ?
 WHERE id = ?
`

type TouchSessionParams struct {
	LastUsedAt int64
	ExpiresAt  int64
	ID         string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastUsedAt, arg.ExpiresAt, arg.ID)
	return err
}
