// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const expireEphemeralTokensIdle = `-- name: ExpireEphemeralTokensIdle :execrows
UPDATE listener_tokens
   SET revoked_at = ?
 WHERE ephemeral = 1
   AND revoked_at IS NULL
   AND ((last_used_at IS NOT NULL AND last_used_at < ?)
     OR (last_used_at IS NULL  AND created_at < ?))
`

type ExpireEphemeralTokensIdleParams struct {
	RevokedAt  sql.NullInt64
	LastUsedAt sql.NullInt64
	CreatedAt  int64
}

func (q *Queries) ExpireEphemeralTokensIdle(ctx context.Context, arg ExpireEphemeralTokensIdleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireEphemeralTokensIdle, arg.RevokedAt, arg.LastUsedAt, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getToken = `-- name: GetToken :one
SELECT id, name, scopes, secret_hash, created_at, last_used_at, revoked_at,
       owner_user_id, kind, ephemeral, expires_at
  FROM listener_tokens WHERE id = ?
`

func (q *Queries) GetToken(ctx context.Context, id string) (ListenerToken, error) {
	row := q.db.QueryRowContext(ctx, getToken, id)
	var i ListenerToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scopes,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.OwnerUserID,
		&i.Kind,
		&i.Ephemeral,
		&i.ExpiresAt,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO listener_tokens
  (id, name, scopes, secret_hash, created_at,
   owner_user_id, kind, ephemeral, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTokenParams struct {
	ID          string
	Name        string
	Scopes      string
	SecretHash  string
	CreatedAt   int64
	OwnerUserID sql.NullString
	Kind        string
	Ephemeral   int64
	ExpiresAt   sql.NullInt64
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertToken,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.SecretHash,
		arg.CreatedAt,
		arg.OwnerUserID,
		arg.Kind,
		arg.Ephemeral,
		arg.ExpiresAt,
	)
	return err
}

const listActiveTokens = `-- name: ListActiveTokens :many
SELECT id, name, scopes, secret_hash, created_at, last_used_at, revoked_at,
       owner_user_id, kind, ephemeral, expires_at
  FROM listener_tokens
 WHERE revoked_at IS NULL
`

func (q *Queries) ListActiveTokens(ctx context.Context) ([]ListenerToken, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListenerToken
	for rows.Next() {
		var i ListenerToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.SecretHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.OwnerUserID,
			&i.Kind,
			&i.Ephemeral,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemTokens = `-- name: ListSystemTokens :many
SELECT id, name, scopes, secret_hash, created_at, last_used_at, revoked_at,
       owner_user_id, kind, ephemeral, expires_at
  FROM listener_tokens
 WHERE owner_user_id IS NULL
   AND (?1 = 1 OR revoked_at IS NULL)
 ORDER BY created_at DESC
`

func (q *Queries) ListSystemTokens(ctx context.Context, includeRevoked interface{}) ([]ListenerToken, error) {
	rows, err := q.db.QueryContext(ctx, listSystemTokens, includeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListenerToken
	for rows.Next() {
		var i ListenerToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.SecretHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.OwnerUserID,
			&i.Kind,
			&i.Ephemeral,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, name, scopes, secret_hash, created_at, last_used_at, revoked_at,
       owner_user_id, kind, ephemeral, expires_at
  FROM listener_tokens
 WHERE (?1 = 1 OR revoked_at IS NULL)
 ORDER BY created_at DESC
`

func (q *Queries) ListTokens(ctx context.Context, includeRevoked interface{}) ([]ListenerToken, error) {
	rows, err := q.db.QueryContext(ctx, listTokens, includeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListenerToken
	for rows.Next() {
		var i ListenerToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.SecretHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.OwnerUserID,
			&i.Kind,
			&i.Ephemeral,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByOwner = `-- name: ListTokensByOwner :many
SELECT id, name, scopes, secret_hash, created_at, last_used_at, revoked_at,
       owner_user_id, kind, ephemeral, expires_at
  FROM listener_tokens
 WHERE owner_user_id = ?
   AND (?2 = 1 OR revoked_at IS NULL)
 ORDER BY created_at DESC
`

type ListTokensByOwnerParams struct {
	OwnerUserID    sql.NullString
	IncludeRevoked interface{}
}

func (q *Queries) ListTokensByOwner(ctx context.Context, arg ListTokensByOwnerParams) ([]ListenerToken, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByOwner, arg.OwnerUserID, arg.IncludeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListenerToken
	for rows.Next() {
		var i ListenerToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.SecretHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.OwnerUserID,
			&i.Kind,
			&i.Ephemeral,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE listener_tokens SET revoked_at = ?
 WHERE id = ? AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt sql.NullInt64
	ID        string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeTokensByOwner = `-- name: RevokeTokensByOwner :execrows
UPDATE listener_tokens
   SET revoked_at = ?
 WHERE owner_user_id = ? AND revoked_at IS NULL
`

type RevokeTokensByOwnerParams struct {
	RevokedAt   sql.NullInt64
	OwnerUserID sql.NullString
}

func (q *Queries) RevokeTokensByOwner(ctx context.Context, arg RevokeTokensByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeTokensByOwner, arg.RevokedAt, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE listener_tokens SET last_used_at = ? WHERE id = ?
`

type TouchTokenLastUsedParams struct {
	LastUsedAt sql.NullInt64
	ID         string
}

func (q *Queries) TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchTokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}

const updateTokenOwner = `-- name: UpdateTokenOwner :execrows
UPDATE listener_tokens SET owner_user_id = ? WHERE id = ?
`

type UpdateTokenOwnerParams struct {
	OwnerUserID sql.NullString
	ID          string
}

func (q *Queries) UpdateTokenOwner(ctx context.Context, arg UpdateTokenOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTokenOwner, arg.OwnerUserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
