// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) AS n FROM users WHERE role = 'admin' AND deactivated_at IS NULL
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countActiveAdminsExcluding = `-- name: CountActiveAdminsExcluding :one
SELECT COUNT(*) AS n FROM users
 WHERE role = 'admin' AND deactivated_at IS NULL AND id != ?
`

func (q *Queries) CountActiveAdminsExcluding(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdminsExcluding, id)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS n FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deactivateUser = `-- name: DeactivateUser :execrows
UPDATE users SET deactivated_at = ? WHERE id = ? AND deactivated_at IS NULL
`

type DeactivateUserParams struct {
	DeactivatedAt sql.NullInt64
	ID            string
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateUser, arg.DeactivatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, password_hash, default_scopes,
       created_at, deactivated_at, external_id
  FROM users WHERE email = ? COLLATE NOCASE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.DefaultScopes,
		&i.CreatedAt,
		&i.DeactivatedAt,
		&i.ExternalID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, password_hash, default_scopes,
       created_at, deactivated_at, external_id
  FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.DefaultScopes,
		&i.CreatedAt,
		&i.DeactivatedAt,
		&i.ExternalID,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users
  (id, email, name, role, password_hash, default_scopes,
   created_at, deactivated_at, external_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUserParams struct {
	ID            string
	Email         string
	Name          string
	Role          string
	PasswordHash  string
	DefaultScopes string
	CreatedAt     int64
	DeactivatedAt sql.NullInt64
	ExternalID    sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.DefaultScopes,
		arg.CreatedAt,
		arg.DeactivatedAt,
		arg.ExternalID,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, password_hash, default_scopes,
       created_at, deactivated_at, external_id
  FROM users
 ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.DefaultScopes,
			&i.CreatedAt,
			&i.DeactivatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, email, name, role, password_hash, default_scopes,
       created_at, deactivated_at, external_id
  FROM users
 WHERE role = ?
 ORDER BY created_at ASC
`

func (q *Queries) ListUsersByRole(ctx context.Context, role string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.DefaultScopes,
			&i.CreatedAt,
			&i.DeactivatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateUser = `-- name: ReactivateUser :execrows
UPDATE users SET deactivated_at = NULL WHERE id = ?
`

func (q *Queries) ReactivateUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, reactivateUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :execrows
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordHashParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserPasswordHash, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users
   SET name = ?, default_scopes = ?
 WHERE id = ?
`

type UpdateUserProfileParams struct {
	Name          string
	DefaultScopes string
	ID            string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserProfile, arg.Name, arg.DefaultScopes, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
