package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"

	"github.com/onebusaway/hooks/internal/store/sqlcgen"
)

func inviteFromGen(r sqlcgen.Invite) (Invite, error) {
	inv := Invite{
		Code:             r.Code,
		Role:             Role(r.Role),
		CreatedByUserID:  ptrFromNullString(r.CreatedByUserID),
		Bootstrap:        r.Bootstrap != 0,
		CreatedAt:        time.Unix(0, r.CreatedAt).UTC(),
		ExpiresAt:        timePtrFromNullInt64(r.ExpiresAt),
		ConsumedAt:       timePtrFromNullInt64(r.ConsumedAt),
		ConsumedByUserID: ptrFromNullString(r.ConsumedByUserID),
	}
	if err := json.Unmarshal([]byte(r.DefaultScopes), &inv.DefaultScopes); err != nil {
		return Invite{}, err
	}
	if inv.DefaultScopes == nil {
		inv.DefaultScopes = []string{}
	}
	return inv, nil
}

func inviteToInsertParams(inv Invite) (sqlcgen.InsertInviteParams, error) {
	scopes, err := json.Marshal(scopesOrEmpty(inv.DefaultScopes))
	if err != nil {
		return sqlcgen.InsertInviteParams{}, err
	}
	bootstrap := int64(0)
	if inv.Bootstrap {
		bootstrap = 1
	}
	return sqlcgen.InsertInviteParams{
		Code:             inv.Code,
		Role:             string(inv.Role),
		DefaultScopes:    string(scopes),
		CreatedByUserID:  nullStringPtr(inv.CreatedByUserID),
		Bootstrap:        bootstrap,
		CreatedAt:        inv.CreatedAt.UTC().UnixNano(),
		ExpiresAt:        nullInt64FromTime(inv.ExpiresAt),
		ConsumedAt:       nullInt64FromTime(inv.ConsumedAt),
		ConsumedByUserID: nullStringPtr(inv.ConsumedByUserID),
	}, nil
}

func (s *SQLite) InsertInvite(ctx context.Context, inv Invite) error {
	if inv.Code == "" {
		return errors.New("InsertInvite: empty code")
	}
	if inv.CreatedAt.IsZero() {
		inv.CreatedAt = time.Now().UTC()
	}
	params, err := inviteToInsertParams(inv)
	if err != nil {
		return err
	}
	return s.q.InsertInvite(ctx, params)
}

func (s *SQLite) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row, err := s.q.GetInviteByCode(ctx, code)
	if errors.Is(err, sql.ErrNoRows) {
		return Invite{}, ErrNotFound
	}
	if err != nil {
		return Invite{}, err
	}
	return inviteFromGen(row)
}

func (s *SQLite) MarkInviteConsumed(ctx context.Context, code, byUser string, at time.Time) error {
	n, err := s.q.MarkInviteConsumed(ctx, sqlcgen.MarkInviteConsumedParams{
		ConsumedAt:       nullInt64FromUnix(at),
		ConsumedByUserID: sql.NullString{String: byUser, Valid: true},
		Code:             code,
	})
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *SQLite) MarkBootstrapInvitesConsumed(ctx context.Context, byUser string, at time.Time) (int64, error) {
	return s.q.MarkBootstrapInvitesConsumed(ctx, sqlcgen.MarkBootstrapInvitesConsumedParams{
		ConsumedAt:       nullInt64FromUnix(at),
		ConsumedByUserID: sql.NullString{String: byUser, Valid: true},
	})
}

func (s *SQLite) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := s.q.ListInvites(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]Invite, 0, len(rows))
	for _, r := range rows {
		inv, err := inviteFromGen(r)
		if err != nil {
			return nil, err
		}
		out = append(out, inv)
	}
	return out, nil
}

func (s *SQLite) ListInvitesByConsumed(ctx context.Context, consumed bool) ([]Invite, error) {
	flag := int64(0)
	if consumed {
		flag = 1
	}
	rows, err := s.q.ListInvitesByConsumed(ctx, flag)
	if err != nil {
		return nil, err
	}
	out := make([]Invite, 0, len(rows))
	for _, r := range rows {
		inv, err := inviteFromGen(r)
		if err != nil {
			return nil, err
		}
		out = append(out, inv)
	}
	return out, nil
}

func (s *SQLite) DeleteInvite(ctx context.Context, code string) error {
	n, err := s.q.DeleteInvite(ctx, code)
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// EnsureBootstrapInvite is the idempotent insert described in design.md:
// inside a tx, look up the existing bootstrap invite. If none exists OR the
// existing one has expired, replace it with a fresh code generated by
// codeFn() and a fresh now+ttl expiry. If a fresh, unconsumed bootstrap
// invite already exists, return it unchanged.
func (s *SQLite) EnsureBootstrapInvite(ctx context.Context, codeFn func() string, ttl time.Duration, now time.Time) (Invite, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return Invite{}, err
	}
	defer func() { _ = tx.Rollback() }()
	q := s.q.WithTx(tx)

	row, err := q.GetBootstrapInvite(ctx)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		// fall through — no bootstrap row, create one.
	case err != nil:
		return Invite{}, err
	default:
		inv, err := inviteFromGen(row)
		if err != nil {
			return Invite{}, err
		}
		// Active bootstrap row that hasn't expired and isn't consumed?
		if inv.ConsumedAt == nil && (inv.ExpiresAt == nil || inv.ExpiresAt.After(now)) {
			if err := tx.Commit(); err != nil {
				return Invite{}, err
			}
			return inv, nil
		}
		// Expired or consumed bootstrap row — replace it.
		if err := q.DeleteBootstrapInvite(ctx); err != nil {
			return Invite{}, err
		}
	}

	exp := now.Add(ttl)
	fresh := Invite{
		Code:          codeFn(),
		Role:          RoleAdmin,
		DefaultScopes: []string{},
		Bootstrap:     true,
		CreatedAt:     now,
		ExpiresAt:     &exp,
	}
	params, err := inviteToInsertParams(fresh)
	if err != nil {
		return Invite{}, err
	}
	if err := q.InsertInvite(ctx, params); err != nil {
		return Invite{}, err
	}
	if err := tx.Commit(); err != nil {
		return Invite{}, err
	}
	return fresh, nil
}

// SignupTx is the atomic invite-consume + user-insert flow described in
// design.md. It marks the invite consumed (returning ErrInviteConsumed if
// already consumed), inserts the user, and (when applicable) marks any
// bootstrap invite consumed in the same tx. Roll back on user-insert
// failure leaves the invite unconsumed.
func (s *SQLite) SignupTx(ctx context.Context, code string, u User, now time.Time) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	q := s.q.WithTx(tx)

	// Insert the user first so the FK references from invites.consumed_by_user_id
	// resolve at statement time. Concurrent signups against the same code race
	// on email-uniqueness AND consumed_at-IS-NULL; whichever tx commits first
	// wins, the rest see ErrInviteConsumed (or a unique-violation on email).
	scopes, err := json.Marshal(scopesOrEmpty(u.DefaultScopes))
	if err != nil {
		return err
	}
	role := string(u.Role)
	if role == "" {
		role = string(RoleUser)
	}
	if err := q.InsertUser(ctx, sqlcgen.InsertUserParams{
		ID:            u.ID,
		Email:         u.Email,
		Name:          u.Name,
		Role:          role,
		PasswordHash:  u.PasswordHash,
		DefaultScopes: string(scopes),
		CreatedAt:     u.CreatedAt.UTC().UnixNano(),
		DeactivatedAt: nullInt64FromTime(u.DeactivatedAt),
		ExternalID:    nullStringPtr(u.ExternalID),
	}); err != nil {
		return err
	}

	n, err := q.MarkInviteConsumed(ctx, sqlcgen.MarkInviteConsumedParams{
		ConsumedAt:       nullInt64FromUnix(now),
		ConsumedByUserID: sql.NullString{String: u.ID, Valid: true},
		Code:             code,
	})
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrInviteConsumed
	}

	// Always sweep bootstrap invites: a fresh signup retires the bootstrap
	// row (if any) regardless of which invite was used.
	if _, err := q.MarkBootstrapInvitesConsumed(ctx, sqlcgen.MarkBootstrapInvitesConsumedParams{
		ConsumedAt:       nullInt64FromUnix(now),
		ConsumedByUserID: sql.NullString{String: u.ID, Valid: true},
	}); err != nil {
		return err
	}

	return tx.Commit()
}

// ErrInviteConsumed is returned when MarkInviteConsumed (or SignupTx) finds
// the invite already consumed.
var ErrInviteConsumed = errors.New("store: invite already consumed")
